### ISSUE TITLE
change the binary name

### ISSUE THREAD

**Issue by muralikodali** [jftuga/dtdiff#5]
there is an existing binary with the same name.
change of the binary name requested.

https://manpages.debian.org/testing/device-tree-compiler/dtdiff.1.en.html

**Comment by jftuga** [comment]
What name would you suggest?

**Comment by ccoVeille** [comment]
I agree that the tool name doesn't help to understand what it does yet

Maybe something mixing the following words:
- dates
- difference
- delay
- delta
- CLI
- helper
- magic
- verse (like universe)
- tool (I dislike it)

Diff is too connoted with file difference

dates-delta sounds good to me, but I'm only a random guy suggesting things here

**Comment by krosseyed** [comment]
Here is a list with some decent reasons on why its a good name:

1. TimeDelta - This name plays off the idea of calculating the difference between two dates and times.
2. DateDiff - A straightforward name that conveys the purpose of the program: calculating differences in dates and times.
3. ChronoCalc - "Chrono" refers to time, while "Calc" suggests calculation, making this name a fitting combination for the program.
4. TimeSpan - This name emphasizes the idea of calculating spans or durations between different points in time.
5. DateShift - This name implies shifting or adjusting dates and times by a certain duration or offset.
6. TemporalDiff - "Temporal" refers to time, while "Diff" is short for difference, making this name a clever combination.
7. ClockCalc - Another name that plays off the idea of calculating differences in clock-related data (dates, times, durations).
8. Durationizer - This name emphasizes the program's ability to calculate and output durations between different points in time.
9. TimeGap - A simple, intuitive name that conveys the idea of calculating gaps or differences in time.
10. DateOffset - This name suggests offsetting or adjusting dates by a certain duration or interval.
11. DateDelta - As mentioned, this name combines "dates" and "delta", which seems fitting for the program.
12. ChronoCleave - This name plays off the idea of calculating differences (cleave) in time (chrono), with a nod to the magical connotations of "magic".
13. DateDiverge - This name emphasizes the idea of dates diverging or moving away from each other, which fits well with the program's purpose.
14. DeltaVerse - Combining "delta" and "verse" (universe) creates a name that sounds quite fitting for a tool that works with dates and times.

**Comment by krosseyed** [comment]
I am partial to ClockDiffCalc, or cdc for the cli instantiation.

**Comment by jftuga** [comment]
I agree that `diff` has a file related connotation and therefore may not be the best name for this project.

I asked an LLM this question:

```
I've written an open source program and need you help coming up with a clear, 
concise name for the software.  The program answers 2 types of questions: 
1. What is the duration between two different dates and/or times?
2. What is the datetime when adding or subtracting a duration?
```

This was the response:

```
TimeSolver
DateCalc
ChronoQuery
DurationMaster
TimeDelta
DateTimeWizard
ChronoCompute
TimeSpanSolver
DateTimeMate
ChronoCalc
```

A follow-up question was asked:

```
I definitely want to use a name that conveys that the program works on both 
dates and times - not just one or the other. 
```

The LLM's answer:

```
    DateTimeSolver
    ChronoMaster
    DateTimeCalc
    ChronoDelta
    DateTimeQuery
    ChronoMate
    DateTimeWizard
    TimeSpanCalc
    ChronoSolver
    DateTimeManager

These names aim to highlight the program's functionality with both dates and times.
```


One of the reasons that I like `DateTimeMate` because `date` and `mate` rhyme, possibly making it more memorable.  I ran a [search](https://www.google.com/search?udm=14&q="DateTimeMate") for "DateTimeMate" with double-quotes and actually received only one search result, which would mean this name would avoid collisions with previous work.  The binary could then be named `dtmate`, which judging by a similar [search](https://www.google.com/search?udm=14&q="dtmate"), would also not have any name collisions.

@muralikodali @ccoVeille @krosseyed what do you think of this new name?

FWIW, I also no longer like the way that the library works and am planning a small API rewrite.  The internal code would not change - just the way a programmer would interface with it.

**Comment by muralikodali** [comment]
as this is a cli binary, for brevity in typing the command in a terminal, can i suggest the name "dtmate" ?

**Comment by krosseyed** [comment]
I like dtmate for the binary name and DateTimeMate for the application name.

**Comment by ccoVeille** [comment]
I also like them. Please check for collision with dtmate and Go go go

**Comment by jftuga** [comment]
I have created a new repo that includes a different CLI binary name.  It also has a much better CLI interface as well as a vastly improved library API.  Therefore, I will soon be archiving this project in favor of [DateTimeMate](https://github.com/jftuga/DateTimeMate). Please consider using it instead along with its command-line program: `dtmate`.

https://github.com/jftuga/DateTimeMate

**Comment by ccoVeille** [comment]
You already had 33 stars. I would have renamed this repository
